language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
before_script:
  tests/travis-build-setup.sh
script: "phpunit -d memory_limit=2048M --verbose -c tests/unit/phpunit.xml --testsuite unit"
matrix:
  fast_finish: true
sudo: false