language: php
php:
  - 5.3.9
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
before_script:
  composer install --prefer-source
script: "phpunit -d memory_limit=1024M --verbose -c tests/unit/phpunit.xml --testsuite unit"
matrix:
  fast_finish: true
sudo: false