language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - cd tests/unit
script: "phpunit -d memory_limit=1024M --verbose -c ./phpunit.xml --testsuite quick"
